#!/bin/bash

SCRIPT=$1

if [ -z "$SCRIPT" ]; then
    echo "❌ Usage: bash install <script.sh>"
    exit 1
fi

chmod +x "$SCRIPT"
BASENAME=$(basename "$SCRIPT" .sh)
sudo cp "$SCRIPT" /usr/local/bin/$BASENAME

# Simulate loading bar from 1% to 100%
echo -n "Loading: "
for i in {1..100}
do
    echo -ne "\rLoading: $i%"
    sleep 0.03
done
echo -e "\n\n\e[1;32mLoading Complete.\e[0m"
sleep 1

echo -e "\n\e[1;33mInstalling Toolkit...\e[0m"
sleep 1

echo "✅ Installed globally! Run it using: $BASENAME"
echo -e "\n\e[1;32mToolkit Installed Successfully C5 INJECTOR in ~/toolkit\e[0m"
